package au.edu.anu.metadatastores.datamodel.harvester;

// Generated 12/02/2013 3:26:07 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * HarvestContent generated by hbm2java
 */
@Entity
@Table(name = "harvest_content", schema = "public")
public class HarvestContent implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	
	private Long hid;
	private String identifier;
	private String system;
	private String content;

	public HarvestContent() {
	}

	public HarvestContent(Long hid, String identifier, String system,
			String content) {
		this.hid = hid;
		this.identifier = identifier;
		this.system = system;
		this.content = content;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "hid", unique = true, nullable = false)
	public Long getHid() {
		return this.hid;
	}

	public void setHid(Long hid) {
		this.hid = hid;
	}

	@Column(name = "identifier", nullable = false)
	public String getIdentifier() {
		return this.identifier;
	}

	public void setIdentifier(String identifier) {
		this.identifier = identifier;
	}

	@Column(name = "system", nullable = false, length = 20)
	public String getSystem() {
		return this.system;
	}

	public void setSystem(String system) {
		this.system = system;
	}

	@Column(name = "content", nullable = false)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

}
