package au.edu.anu.metadatastores.datamodel.harvester;

// Generated 12/02/2013 3:26:07 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Location generated by hbm2java
 */
@Entity
@Table(name = "location", schema = "public")
public class Location implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	private Long lid;
	private String system;
	private String url;
	private String metadataPrefix;
	private Date lastHarvestDate;
	private Long harvestFreq;
	private Date origHarvestDate;

	public Location() {
	}

	public Location(Long lid, String system, String url, String metadataPrefix) {
		this.lid = lid;
		this.system = system;
		this.url = url;
		this.metadataPrefix = metadataPrefix;
	}

	public Location(Long lid, String system, String url, String metadataPrefix,
			Date lastHarvestDate, Long harvestFreq, Date origHarvestDate) {
		this.lid = lid;
		this.system = system;
		this.url = url;
		this.metadataPrefix = metadataPrefix;
		this.lastHarvestDate = lastHarvestDate;
		this.harvestFreq = harvestFreq;
		this.origHarvestDate = origHarvestDate;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "lid", unique = true, nullable = false)
	public Long getLid() {
		return this.lid;
	}

	public void setLid(Long lid) {
		this.lid = lid;
	}

	@Column(name = "system", nullable = false, length = 20)
	public String getSystem() {
		return this.system;
	}

	public void setSystem(String system) {
		this.system = system;
	}

	@Column(name = "url", nullable = false)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "metadata_prefix", nullable = false)
	public String getMetadataPrefix() {
		return this.metadataPrefix;
	}

	public void setMetadataPrefix(String metadataPrefix) {
		this.metadataPrefix = metadataPrefix;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_harvest_date", length = 35)
	public Date getLastHarvestDate() {
		return this.lastHarvestDate;
	}

	public void setLastHarvestDate(Date lastHarvestDate) {
		this.lastHarvestDate = lastHarvestDate;
	}

	@Column(name = "harvest_freq")
	public Long getHarvestFreq() {
		return this.harvestFreq;
	}

	public void setHarvestFreq(Long harvestFreq) {
		this.harvestFreq = harvestFreq;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "orig_harvest_date", length = 35)
	public Date getOrigHarvestDate() {
		return this.origHarvestDate;
	}

	public void setOrigHarvestDate(Date origHarvestDate) {
		this.origHarvestDate = origHarvestDate;
	}

}
