package au.edu.anu.metadatastores.datamodel.aries.grants;

// Generated 10/01/2013 2:39:04 PM by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ContractsGrantsDepartments generated by hbm2java
 */
@Entity
@Table(name = "contracts_grants_departments")
public class ContractsGrantsDepartments implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	private ContractsGrantsDepartmentsId id;

	public ContractsGrantsDepartments() {
	}

	public ContractsGrantsDepartments(ContractsGrantsDepartmentsId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "chrPrimary", column = @Column(name = "chrPrimary", length = 45)),
			@AttributeOverride(name = "chrDepartmentCode", column = @Column(name = "chrDepartmentCode", length = 45)),
			@AttributeOverride(name = "chrContractDepartmentCode", column = @Column(name = "chrContractDepartmentCode", length = 45)),
			@AttributeOverride(name = "chrContractCode", column = @Column(name = "chrContractCode", length = 45)) })
	public ContractsGrantsDepartmentsId getId() {
		return this.id;
	}

	public void setId(ContractsGrantsDepartmentsId id) {
		this.id = id;
	}

}
