package au.edu.anu.metadatastores.datamodel.aries.grants;

// Generated 10/01/2013 2:39:04 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ContractsGrantsInvestigators generated by hbm2java
 */
@Entity
@Table(name = "contracts_grants_investigators")
public class ContractsGrantsInvestigators implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	
	private String chrContractInvestigatorCode;
	private String chrStaffNumber;
	private String chrRoute;
	private String chrPrimary;
	private ContractsGrantsMain contractsGrantsMain;

	public ContractsGrantsInvestigators() {
	}

	@Id
	@Column(name = "chrContractInvestigatorCode", insertable=false, updatable=false)
	public String getChrContractInvestigatorCode() {
		return this.chrContractInvestigatorCode;
	}

	public void setChrContractInvestigatorCode(
			String chrContractInvestigatorCode) {
		this.chrContractInvestigatorCode = chrContractInvestigatorCode;
	}

	@Column(name = "chrStaffNumber")
	public String getChrStaffNumber() {
		return this.chrStaffNumber;
	}

	public void setChrStaffNumber(String chrStaffNumber) {
		this.chrStaffNumber = chrStaffNumber;
	}

	@Column(name = "chrRoute")
	public String getChrRoute() {
		return this.chrRoute;
	}

	public void setChrRoute(String chrRoute) {
		this.chrRoute = chrRoute;
	}

	@Column(name="chrPrimary")
	public String getChrPrimary() {
		return chrPrimary;
	}

	public void setChrPrimary(String chrPrimary) {
		this.chrPrimary = chrPrimary;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "chrContractCode")
	public ContractsGrantsMain getContractsGrantsMain() {
		return contractsGrantsMain;
	}

	public void setContractsGrantsMain(ContractsGrantsMain contractsGrantsMain) {
		this.contractsGrantsMain = contractsGrantsMain;
	}
}
