package au.edu.anu.metadatastores.datamodel.aries.grants;

// Generated 10/01/2013 2:39:04 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ContractsGrantsDepartmentsId generated by hbm2java
 */
@Embeddable
public class ContractsGrantsDepartmentsId implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	private String chrPrimary;
	private String chrDepartmentCode;
	private String chrContractDepartmentCode;
	private String chrContractCode;

	public ContractsGrantsDepartmentsId() {
	}

	public ContractsGrantsDepartmentsId(String chrPrimary,
			String chrDepartmentCode, String chrContractDepartmentCode,
			String chrContractCode) {
		this.chrPrimary = chrPrimary;
		this.chrDepartmentCode = chrDepartmentCode;
		this.chrContractDepartmentCode = chrContractDepartmentCode;
		this.chrContractCode = chrContractCode;
	}

	@Column(name = "chrPrimary", length = 45)
	public String getChrPrimary() {
		return this.chrPrimary;
	}

	public void setChrPrimary(String chrPrimary) {
		this.chrPrimary = chrPrimary;
	}

	@Column(name = "chrDepartmentCode", length = 45)
	public String getChrDepartmentCode() {
		return this.chrDepartmentCode;
	}

	public void setChrDepartmentCode(String chrDepartmentCode) {
		this.chrDepartmentCode = chrDepartmentCode;
	}

	@Column(name = "chrContractDepartmentCode", length = 45)
	public String getChrContractDepartmentCode() {
		return this.chrContractDepartmentCode;
	}

	public void setChrContractDepartmentCode(String chrContractDepartmentCode) {
		this.chrContractDepartmentCode = chrContractDepartmentCode;
	}

	@Column(name = "chrContractCode", length = 45)
	public String getChrContractCode() {
		return this.chrContractCode;
	}

	public void setChrContractCode(String chrContractCode) {
		this.chrContractCode = chrContractCode;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ContractsGrantsDepartmentsId))
			return false;
		ContractsGrantsDepartmentsId castOther = (ContractsGrantsDepartmentsId) other;

		return ((this.getChrPrimary() == castOther.getChrPrimary()) || (this
				.getChrPrimary() != null && castOther.getChrPrimary() != null && this
				.getChrPrimary().equals(castOther.getChrPrimary())))
				&& ((this.getChrDepartmentCode() == castOther
						.getChrDepartmentCode()) || (this
						.getChrDepartmentCode() != null
						&& castOther.getChrDepartmentCode() != null && this
						.getChrDepartmentCode().equals(
								castOther.getChrDepartmentCode())))
				&& ((this.getChrContractDepartmentCode() == castOther
						.getChrContractDepartmentCode()) || (this
						.getChrContractDepartmentCode() != null
						&& castOther.getChrContractDepartmentCode() != null && this
						.getChrContractDepartmentCode().equals(
								castOther.getChrContractDepartmentCode())))
				&& ((this.getChrContractCode() == castOther
						.getChrContractCode()) || (this.getChrContractCode() != null
						&& castOther.getChrContractCode() != null && this
						.getChrContractCode().equals(
								castOther.getChrContractCode())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getChrPrimary() == null ? 0 : this.getChrPrimary()
						.hashCode());
		result = 37
				* result
				+ (getChrDepartmentCode() == null ? 0 : this
						.getChrDepartmentCode().hashCode());
		result = 37
				* result
				+ (getChrContractDepartmentCode() == null ? 0 : this
						.getChrContractDepartmentCode().hashCode());
		result = 37
				* result
				+ (getChrContractCode() == null ? 0 : this.getChrContractCode()
						.hashCode());
		return result;
	}

}
