package au.edu.anu.metadatastores.datamodel.aries.grants;

// Generated 10/01/2013 2:39:04 PM by Hibernate Tools 4.0.0

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.NotFound;
import org.hibernate.annotations.NotFoundAction;

/**
 * ContractsGrantsMain generated by hbm2java
 */
@Entity
@Table(name = "contracts_grants_main")
public class ContractsGrantsMain implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	
	private String chrContractCode;
	private String chrShortTitle;
	private String chrPrimaryFundsProvider;
	private String chrSchemeRef;
	private String chrGrantStartDate;
	private String chrCompletionDate;
	private String chrStatus;
	//private String chrForcode1;
	private ForCodes forCodes1;
	private String chrForpercentage1;
	//private String chrForcode2;
	private ForCodes forCodes2;
	private String chrForpercentage2;
	//private String chrForcode3;
	private ForCodes forCodes3;
	private String chrForpercentage3;
	private List<ContractsGrantsInvestigators> contractsGrantsInvestigators = new ArrayList<ContractsGrantsInvestigators>();

	public ContractsGrantsMain() {
	}
	
	@Id
	@Column(name = "chrContractCode")
	public String getChrContractCode() {
		return chrContractCode;
	}

	public void setChrContractCode(String chrContractCode) {
		this.chrContractCode = chrContractCode;
	}

	@Column(name = "chrShortTitle")
	public String getChrShortTitle() {
		return chrShortTitle;
	}

	public void setChrShortTitle(String chrShortTitle) {
		this.chrShortTitle = chrShortTitle;
	}

	@Column(name = "chrPrimaryFundsProvider")
	public String getChrPrimaryFundsProvider() {
		return chrPrimaryFundsProvider;
	}

	public void setChrPrimaryFundsProvider(String chrPrimaryFundsProvider) {
		this.chrPrimaryFundsProvider = chrPrimaryFundsProvider;
	}

	@Column(name = "chrSchemeRef")
	public String getChrSchemeRef() {
		return chrSchemeRef;
	}

	public void setChrSchemeRef(String chrSchemeRef) {
		this.chrSchemeRef = chrSchemeRef;
	}

	@Column(name = "chrGrantStartDate")
	public String getChrGrantStartDate() {
		return chrGrantStartDate;
	}

	public void setChrGrantStartDate(String chrGrantStartDate) {
		this.chrGrantStartDate = chrGrantStartDate;
	}

	@Column(name = "chrCompletionDate")
	public String getChrCompletionDate() {
		return chrCompletionDate;
	}

	public void setChrCompletionDate(String chrCompletionDate) {
		this.chrCompletionDate = chrCompletionDate;
	}
	
	@Column(name = "chrStatus")
	public String getChrStatus() {
		return chrStatus;
	}

	public void setChrStatus(String chrStatus) {
		this.chrStatus = chrStatus;
	}

	/*
	@Column(name = "chrFORcode1")
	public String getChrForcode1() {
		return chrForcode1;
	}

	public void setChrForcode1(String chrForcode1) {
		this.chrForcode1 = chrForcode1;
	}
*/
	@Column(name = "chrFORpercentage1")
	public String getChrForpercentage1() {
		return chrForpercentage1;
	}

	public void setChrForpercentage1(String chrForpercentage1) {
		this.chrForpercentage1 = chrForpercentage1;
	}
/*
	@Column(name = "chrFORcode2")
	public String getChrForcode2() {
		return chrForcode2;
	}

	public void setChrForcode2(String chrForcode2) {
		this.chrForcode2 = chrForcode2;
	}
*/
	@Column(name = "chrFORpercentage2")
	public String getChrForpercentage2() {
		return chrForpercentage2;
	}

	public void setChrForpercentage2(String chrForpercentage2) {
		this.chrForpercentage2 = chrForpercentage2;
	}
/*
	@Column(name = "chrFORcode3")
	public String getChrForcode3() {
		return chrForcode3;
	}

	public void setChrForcode3(String chrForcode3) {
		this.chrForcode3 = chrForcode3;
	}
*/
	@Column(name = "chrFORpercentage3")
	public String getChrForpercentage3() {
		return chrForpercentage3;
	}

	public void setChrForpercentage3(String chrForpercentage3) {
		this.chrForpercentage3 = chrForpercentage3;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "contractsGrantsMain")
	public List<ContractsGrantsInvestigators> getContractsGrantsInvestigators() {
		return this.contractsGrantsInvestigators;
	}
	
	public void setContractsGrantsInvestigators(List<ContractsGrantsInvestigators> contractsGrantsInvestigators) {
		this.contractsGrantsInvestigators = contractsGrantsInvestigators;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "chrFORcode1")
	@NotFound(action=NotFoundAction.IGNORE)
	public ForCodes getForCodes1() {
		return forCodes1;
	}

	public void setForCodes1(ForCodes forCodes1) {
		this.forCodes1 = forCodes1;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "chrFORcode2")
	@NotFound(action=NotFoundAction.IGNORE)
	public ForCodes getForCodes2() {
		return forCodes2;
	}

	public void setForCodes2(ForCodes forCodes2) {
		this.forCodes2 = forCodes2;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "chrFORcode3")
	@NotFound(action=NotFoundAction.IGNORE)
	public ForCodes getForCodes3() {
		return forCodes3;
	}

	public void setForCodes3(ForCodes forCodes3) {
		this.forCodes3 = forCodes3;
	}
}
