package au.edu.anu.metadatastores.datamodel.aries.grants;

// Generated 10/01/2013 2:39:04 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ContractsGrantsCountriesId generated by hbm2java
 */
@Embeddable
public class ContractsGrantsCountriesId implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	private String chrContractCode;
	private String chrContractCountryCode;
	private String chrCountryName;

	public ContractsGrantsCountriesId() {
	}

	public ContractsGrantsCountriesId(String chrContractCode,
			String chrContractCountryCode, String chrCountryName) {
		this.chrContractCode = chrContractCode;
		this.chrContractCountryCode = chrContractCountryCode;
		this.chrCountryName = chrCountryName;
	}

	@Column(name = "chrContractCode", length = 45)
	public String getChrContractCode() {
		return this.chrContractCode;
	}

	public void setChrContractCode(String chrContractCode) {
		this.chrContractCode = chrContractCode;
	}

	@Column(name = "chrContractCountryCode", length = 45)
	public String getChrContractCountryCode() {
		return this.chrContractCountryCode;
	}

	public void setChrContractCountryCode(String chrContractCountryCode) {
		this.chrContractCountryCode = chrContractCountryCode;
	}

	@Column(name = "chrCountryName", length = 45)
	public String getChrCountryName() {
		return this.chrCountryName;
	}

	public void setChrCountryName(String chrCountryName) {
		this.chrCountryName = chrCountryName;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ContractsGrantsCountriesId))
			return false;
		ContractsGrantsCountriesId castOther = (ContractsGrantsCountriesId) other;

		return ((this.getChrContractCode() == castOther.getChrContractCode()) || (this
				.getChrContractCode() != null
				&& castOther.getChrContractCode() != null && this
				.getChrContractCode().equals(castOther.getChrContractCode())))
				&& ((this.getChrContractCountryCode() == castOther
						.getChrContractCountryCode()) || (this
						.getChrContractCountryCode() != null
						&& castOther.getChrContractCountryCode() != null && this
						.getChrContractCountryCode().equals(
								castOther.getChrContractCountryCode())))
				&& ((this.getChrCountryName() == castOther.getChrCountryName()) || (this
						.getChrCountryName() != null
						&& castOther.getChrCountryName() != null && this
						.getChrCountryName().equals(
								castOther.getChrCountryName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getChrContractCode() == null ? 0 : this.getChrContractCode()
						.hashCode());
		result = 37
				* result
				+ (getChrContractCountryCode() == null ? 0 : this
						.getChrContractCountryCode().hashCode());
		result = 37
				* result
				+ (getChrCountryName() == null ? 0 : this.getChrCountryName()
						.hashCode());
		return result;
	}

}
