package au.edu.anu.metadatastores.datamodel.aries.grants;

// Generated 10/01/2013 2:39:04 PM by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * ContractsGrantsCountries generated by hbm2java
 */
@Entity
@Table(name = "contracts_grants_countries")
public class ContractsGrantsCountries implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	private ContractsGrantsCountriesId id;

	public ContractsGrantsCountries() {
	}

	public ContractsGrantsCountries(ContractsGrantsCountriesId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "chrContractCode", column = @Column(name = "chrContractCode", length = 45)),
			@AttributeOverride(name = "chrContractCountryCode", column = @Column(name = "chrContractCountryCode", length = 45)),
			@AttributeOverride(name = "chrCountryName", column = @Column(name = "chrCountryName", length = 45)) })
	public ContractsGrantsCountriesId getId() {
		return this.id;
	}

	public void setId(ContractsGrantsCountriesId id) {
		this.id = id;
	}

}
