package au.edu.anu.metadatastores.datamodel.aries.grants;

// Generated 10/01/2013 2:39:04 PM by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Departments generated by hbm2java
 */
@Entity
@Table(name = "departments")
public class Departments implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	private DepartmentsId id;
	private String chrSchoolCode;

	public Departments() {
	}

	public Departments(DepartmentsId id) {
		this.id = id;
	}

	public Departments(DepartmentsId id, String chrSchoolCode) {
		this.id = id;
		this.chrSchoolCode = chrSchoolCode;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "chrTier3name", column = @Column(name = "chrTier3Name", nullable = false, length = 55)),
			@AttributeOverride(name = "chrTier1code", column = @Column(name = "chrTier1Code", nullable = false, length = 45)),
			@AttributeOverride(name = "chrTier2code", column = @Column(name = "chrTier2Code", nullable = false, length = 55)),
			@AttributeOverride(name = "chrTier3code", column = @Column(name = "chrTier3Code", nullable = false, length = 45)),
			@AttributeOverride(name = "chrCollegeCode", column = @Column(name = "chrCollegeCode", nullable = false, length = 45)) })
	public DepartmentsId getId() {
		return this.id;
	}

	public void setId(DepartmentsId id) {
		this.id = id;
	}

	@Column(name = "chrSchoolCode", length = 45)
	public String getChrSchoolCode() {
		return this.chrSchoolCode;
	}

	public void setChrSchoolCode(String chrSchoolCode) {
		this.chrSchoolCode = chrSchoolCode;
	}

}
