package au.edu.anu.metadatastores.datamodel.aries.grants;

// Generated 10/01/2013 2:39:04 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * FacultyschoolcentreId generated by hbm2java
 */
@Embeddable
public class FacultyschoolcentreId implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	private String chrTierCode;
	private String chrTier2name;
	private String chrTier2code;
	private String chrDateStatus;
	private String chrAou;
	private String chrFinanceCode;
	private String chrHraou;

	public FacultyschoolcentreId() {
	}

	public FacultyschoolcentreId(String chrTierCode, String chrTier2name,
			String chrTier2code, String chrDateStatus, String chrAou,
			String chrFinanceCode, String chrHraou) {
		this.chrTierCode = chrTierCode;
		this.chrTier2name = chrTier2name;
		this.chrTier2code = chrTier2code;
		this.chrDateStatus = chrDateStatus;
		this.chrAou = chrAou;
		this.chrFinanceCode = chrFinanceCode;
		this.chrHraou = chrHraou;
	}

	@Column(name = "chrTierCode", length = 45)
	public String getChrTierCode() {
		return this.chrTierCode;
	}

	public void setChrTierCode(String chrTierCode) {
		this.chrTierCode = chrTierCode;
	}

	@Column(name = "chrTier2Name", length = 45)
	public String getChrTier2name() {
		return this.chrTier2name;
	}

	public void setChrTier2name(String chrTier2name) {
		this.chrTier2name = chrTier2name;
	}

	@Column(name = "chrTier2Code", length = 45)
	public String getChrTier2code() {
		return this.chrTier2code;
	}

	public void setChrTier2code(String chrTier2code) {
		this.chrTier2code = chrTier2code;
	}

	@Column(name = "chrDateStatus", length = 45)
	public String getChrDateStatus() {
		return this.chrDateStatus;
	}

	public void setChrDateStatus(String chrDateStatus) {
		this.chrDateStatus = chrDateStatus;
	}

	@Column(name = "chrAOU", length = 45)
	public String getChrAou() {
		return this.chrAou;
	}

	public void setChrAou(String chrAou) {
		this.chrAou = chrAou;
	}

	@Column(name = "chrFinanceCode", length = 45)
	public String getChrFinanceCode() {
		return this.chrFinanceCode;
	}

	public void setChrFinanceCode(String chrFinanceCode) {
		this.chrFinanceCode = chrFinanceCode;
	}

	@Column(name = "chrHRAOU", length = 45)
	public String getChrHraou() {
		return this.chrHraou;
	}

	public void setChrHraou(String chrHraou) {
		this.chrHraou = chrHraou;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FacultyschoolcentreId))
			return false;
		FacultyschoolcentreId castOther = (FacultyschoolcentreId) other;

		return ((this.getChrTierCode() == castOther.getChrTierCode()) || (this
				.getChrTierCode() != null && castOther.getChrTierCode() != null && this
				.getChrTierCode().equals(castOther.getChrTierCode())))
				&& ((this.getChrTier2name() == castOther.getChrTier2name()) || (this
						.getChrTier2name() != null
						&& castOther.getChrTier2name() != null && this
						.getChrTier2name().equals(castOther.getChrTier2name())))
				&& ((this.getChrTier2code() == castOther.getChrTier2code()) || (this
						.getChrTier2code() != null
						&& castOther.getChrTier2code() != null && this
						.getChrTier2code().equals(castOther.getChrTier2code())))
				&& ((this.getChrDateStatus() == castOther.getChrDateStatus()) || (this
						.getChrDateStatus() != null
						&& castOther.getChrDateStatus() != null && this
						.getChrDateStatus()
						.equals(castOther.getChrDateStatus())))
				&& ((this.getChrAou() == castOther.getChrAou()) || (this
						.getChrAou() != null && castOther.getChrAou() != null && this
						.getChrAou().equals(castOther.getChrAou())))
				&& ((this.getChrFinanceCode() == castOther.getChrFinanceCode()) || (this
						.getChrFinanceCode() != null
						&& castOther.getChrFinanceCode() != null && this
						.getChrFinanceCode().equals(
								castOther.getChrFinanceCode())))
				&& ((this.getChrHraou() == castOther.getChrHraou()) || (this
						.getChrHraou() != null
						&& castOther.getChrHraou() != null && this
						.getChrHraou().equals(castOther.getChrHraou())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getChrTierCode() == null ? 0 : this.getChrTierCode()
						.hashCode());
		result = 37
				* result
				+ (getChrTier2name() == null ? 0 : this.getChrTier2name()
						.hashCode());
		result = 37
				* result
				+ (getChrTier2code() == null ? 0 : this.getChrTier2code()
						.hashCode());
		result = 37
				* result
				+ (getChrDateStatus() == null ? 0 : this.getChrDateStatus()
						.hashCode());
		result = 37 * result
				+ (getChrAou() == null ? 0 : this.getChrAou().hashCode());
		result = 37
				* result
				+ (getChrFinanceCode() == null ? 0 : this.getChrFinanceCode()
						.hashCode());
		result = 37 * result
				+ (getChrHraou() == null ? 0 : this.getChrHraou().hashCode());
		return result;
	}

}
