package au.edu.anu.metadatastores.datamodel.aries.grants;

// Generated 10/01/2013 2:39:04 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PicklistChrrouteChrstatusId generated by hbm2java
 */
@Embeddable
public class PicklistChrrouteChrstatusId implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	private String chrRoute;
	private String chrStatus;

	public PicklistChrrouteChrstatusId() {
	}

	public PicklistChrrouteChrstatusId(String chrRoute, String chrStatus) {
		this.chrRoute = chrRoute;
		this.chrStatus = chrStatus;
	}

	@Column(name = "chrRoute", length = 45)
	public String getChrRoute() {
		return this.chrRoute;
	}

	public void setChrRoute(String chrRoute) {
		this.chrRoute = chrRoute;
	}

	@Column(name = "chrStatus", length = 45)
	public String getChrStatus() {
		return this.chrStatus;
	}

	public void setChrStatus(String chrStatus) {
		this.chrStatus = chrStatus;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PicklistChrrouteChrstatusId))
			return false;
		PicklistChrrouteChrstatusId castOther = (PicklistChrrouteChrstatusId) other;

		return ((this.getChrRoute() == castOther.getChrRoute()) || (this
				.getChrRoute() != null && castOther.getChrRoute() != null && this
				.getChrRoute().equals(castOther.getChrRoute())))
				&& ((this.getChrStatus() == castOther.getChrStatus()) || (this
						.getChrStatus() != null
						&& castOther.getChrStatus() != null && this
						.getChrStatus().equals(castOther.getChrStatus())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getChrRoute() == null ? 0 : this.getChrRoute().hashCode());
		result = 37 * result
				+ (getChrStatus() == null ? 0 : this.getChrStatus().hashCode());
		return result;
	}

}
