package au.edu.anu.metadatastores.datamodel.aries.grants;

// Generated 10/01/2013 2:39:04 PM by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * PicklistChrrouteChrstatus generated by hbm2java
 */
@Entity
@Table(name = "picklist_chrroute_chrstatus")
public class PicklistChrrouteChrstatus implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	private PicklistChrrouteChrstatusId id;

	public PicklistChrrouteChrstatus() {
	}

	public PicklistChrrouteChrstatus(PicklistChrrouteChrstatusId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "chrRoute", column = @Column(name = "chrRoute", length = 45)),
			@AttributeOverride(name = "chrStatus", column = @Column(name = "chrStatus", length = 45)) })
	public PicklistChrrouteChrstatusId getId() {
		return this.id;
	}

	public void setId(PicklistChrrouteChrstatusId id) {
		this.id = id;
	}

}
