package au.edu.anu.metadatastores.datamodel.aries.grants;

// Generated 29/01/2013 4:37:31 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Useraccounts generated by hbm2java
 */
@Entity
@Table(name = "useraccounts")
public class Useraccounts implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	private int intSystemCounter;
	private String chrStaffNumber;
	private String chrTitle;
	private String chrFirstname;
	private String chrSurname;
	private String chrFax;
	private String chrTelephone;
	private String chrEmail;
	private String chrForcode1;
	private String chrForpercentage1;
	private String chrForcode2;
	private String chrForpercentage2;
	private String chrForcode3;
	private String chrForpercentage3;
	private String chrDepartmentCode;

	public Useraccounts() {
	}

	public Useraccounts(int intSystemCounter) {
		this.intSystemCounter = intSystemCounter;
	}

	public Useraccounts(int intSystemCounter, String chrStaffNumber,
			String chrTitle, String chrFirstname, String chrSurname,
			String chrFax, String chrTelephone, String chrEmail,
			String chrForcode1, String chrForpercentage1, String chrForcode2,
			String chrForpercentage2, String chrForcode3,
			String chrForpercentage3, String chrDepartmentCode) {
		this.intSystemCounter = intSystemCounter;
		this.chrStaffNumber = chrStaffNumber;
		this.chrTitle = chrTitle;
		this.chrFirstname = chrFirstname;
		this.chrSurname = chrSurname;
		this.chrFax = chrFax;
		this.chrTelephone = chrTelephone;
		this.chrEmail = chrEmail;
		this.chrForcode1 = chrForcode1;
		this.chrForpercentage1 = chrForpercentage1;
		this.chrForcode2 = chrForcode2;
		this.chrForpercentage2 = chrForpercentage2;
		this.chrForcode3 = chrForcode3;
		this.chrForpercentage3 = chrForpercentage3;
		this.chrDepartmentCode = chrDepartmentCode;
	}

	@Id
	@Column(name = "intSystemCounter", unique = true, nullable = false)
	public int getIntSystemCounter() {
		return this.intSystemCounter;
	}

	public void setIntSystemCounter(int intSystemCounter) {
		this.intSystemCounter = intSystemCounter;
	}

	@Column(name = "chrStaffNumber", length = 45)
	public String getChrStaffNumber() {
		return this.chrStaffNumber;
	}

	public void setChrStaffNumber(String chrStaffNumber) {
		this.chrStaffNumber = chrStaffNumber;
	}

	@Column(name = "chrTitle", length = 45)
	public String getChrTitle() {
		return this.chrTitle;
	}

	public void setChrTitle(String chrTitle) {
		this.chrTitle = chrTitle;
	}

	@Column(name = "chrFirstname", length = 45)
	public String getChrFirstname() {
		return this.chrFirstname;
	}

	public void setChrFirstname(String chrFirstname) {
		this.chrFirstname = chrFirstname;
	}

	@Column(name = "chrSurname", length = 45)
	public String getChrSurname() {
		return this.chrSurname;
	}

	public void setChrSurname(String chrSurname) {
		this.chrSurname = chrSurname;
	}

	@Column(name = "chrFax", length = 45)
	public String getChrFax() {
		return this.chrFax;
	}

	public void setChrFax(String chrFax) {
		this.chrFax = chrFax;
	}

	@Column(name = "chrTelephone", length = 45)
	public String getChrTelephone() {
		return this.chrTelephone;
	}

	public void setChrTelephone(String chrTelephone) {
		this.chrTelephone = chrTelephone;
	}

	@Column(name = "chrEmail", length = 45)
	public String getChrEmail() {
		return this.chrEmail;
	}

	public void setChrEmail(String chrEmail) {
		this.chrEmail = chrEmail;
	}

	@Column(name = "chrFORcode1", length = 45)
	public String getChrForcode1() {
		return this.chrForcode1;
	}

	public void setChrForcode1(String chrForcode1) {
		this.chrForcode1 = chrForcode1;
	}

	@Column(name = "chrFORpercentage1", length = 45)
	public String getChrForpercentage1() {
		return this.chrForpercentage1;
	}

	public void setChrForpercentage1(String chrForpercentage1) {
		this.chrForpercentage1 = chrForpercentage1;
	}

	@Column(name = "chrFORcode2", length = 45)
	public String getChrForcode2() {
		return this.chrForcode2;
	}

	public void setChrForcode2(String chrForcode2) {
		this.chrForcode2 = chrForcode2;
	}

	@Column(name = "chrFORpercentage2", length = 45)
	public String getChrForpercentage2() {
		return this.chrForpercentage2;
	}

	public void setChrForpercentage2(String chrForpercentage2) {
		this.chrForpercentage2 = chrForpercentage2;
	}

	@Column(name = "chrFORcode3", length = 45)
	public String getChrForcode3() {
		return this.chrForcode3;
	}

	public void setChrForcode3(String chrForcode3) {
		this.chrForcode3 = chrForcode3;
	}

	@Column(name = "chrFORpercentage3", length = 45)
	public String getChrForpercentage3() {
		return this.chrForpercentage3;
	}

	public void setChrForpercentage3(String chrForpercentage3) {
		this.chrForpercentage3 = chrForpercentage3;
	}

	@Column(name = "chrDepartmentCode", length = 45)
	public String getChrDepartmentCode() {
		return this.chrDepartmentCode;
	}

	public void setChrDepartmentCode(String chrDepartmentCode) {
		this.chrDepartmentCode = chrDepartmentCode;
	}

}
