package au.edu.anu.metadatastores.datamodel.store;

// Generated 27/02/2013 10:39:19 AM by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ItemRelation generated by hbm2java
 */
@Entity
@Table(name = "item_relation", schema = "public")
public class ItemRelation implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	private ItemRelationId id;
	private Item itemByIid;
	private Item itemByRelatedIid;
	private Boolean userUpdated;

	public ItemRelation() {
	}

	public ItemRelation(ItemRelationId id, Item itemByIid, Item itemByRelatedIid) {
		this.id = id;
		this.itemByIid = itemByIid;
		this.itemByRelatedIid = itemByRelatedIid;
	}

	public ItemRelation(ItemRelationId id, Item itemByIid,
			Item itemByRelatedIid, Boolean userUpdated) {
		this.id = id;
		this.itemByIid = itemByIid;
		this.itemByRelatedIid = itemByRelatedIid;
		this.userUpdated = userUpdated;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "iid", column = @Column(name = "iid", nullable = false)),
			@AttributeOverride(name = "relationValue", column = @Column(name = "relation_value", nullable = false)),
			@AttributeOverride(name = "relatedIid", column = @Column(name = "related_iid", nullable = false)) })
	public ItemRelationId getId() {
		return this.id;
	}

	public void setId(ItemRelationId id) {
		this.id = id;
	}

	@ManyToOne//(fetch = FetchType.LAZY)
	@JoinColumn(name = "iid", nullable = false, insertable = false, updatable = false)
	public Item getItemByIid() {
		return this.itemByIid;
	}

	public void setItemByIid(Item itemByIid) {
		this.itemByIid = itemByIid;
	}

	@ManyToOne
	@JoinColumn(name = "related_iid", nullable = false, insertable = false, updatable = false)
	public Item getItemByRelatedIid() {
		return this.itemByRelatedIid;
	}

	public void setItemByRelatedIid(Item itemByRelatedIid) {
		this.itemByRelatedIid = itemByRelatedIid;
	}

	@Column(name = "user_updated")
	public Boolean getUserUpdated() {
		return this.userUpdated;
	}

	public void setUserUpdated(Boolean userUpdated) {
		this.userUpdated = userUpdated;
	}

}
