package au.edu.anu.metadatastores.datamodel.store;

// Generated 27/02/2013 10:39:19 AM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Cascade;
import org.hibernate.annotations.CascadeType;

/**
 * ItemAttribute generated by hbm2java
 */
@Entity
@Table(name = "item_attribute", schema = "public")
public class ItemAttribute implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	
	private Long aid;
	private Item item;
	private ItemAttribute itemAttribute;
	private String attrType;
	private String attrValue;
	private Boolean userUpdated;
	private Date lastModified;
	private Set<ItemAttribute> itemAttributes = new HashSet<ItemAttribute>(0);

	public ItemAttribute() {
	}
	
	public ItemAttribute(Item item, String attrType, String attrValue, Date lastModified) {
		this.item = item;
		this.attrType = attrType;
		this.attrValue = attrValue;
		this.lastModified = lastModified;
	}

	public ItemAttribute(Long aid, Item item, String attrType, String attrValue) {
		this.aid = aid;
		this.item = item;
		this.attrType = attrType;
		this.attrValue = attrValue;
	}

	public ItemAttribute(Long aid, Item item, ItemAttribute itemAttribute,
			String attrType, String attrValue, Boolean userUpdated,
			Date lastModified, Set<ItemAttribute> itemAttributes) {
		this.aid = aid;
		this.item = item;
		this.itemAttribute = itemAttribute;
		this.attrType = attrType;
		this.attrValue = attrValue;
		this.userUpdated = userUpdated;
		this.lastModified = lastModified;
		this.itemAttributes = itemAttributes;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "aid", unique = true, nullable = false)
	public Long getAid() {
		return this.aid;
	}

	public void setAid(Long aid) {
		this.aid = aid;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "iid", nullable = false)
	public Item getItem() {
		return this.item;
	}

	public void setItem(Item item) {
		this.item = item;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "parent_aid")
	public ItemAttribute getItemAttribute() {
		return this.itemAttribute;
	}

	public void setItemAttribute(ItemAttribute itemAttribute) {
		this.itemAttribute = itemAttribute;
	}

	@Column(name = "attr_type", nullable = false, length = 40)
	public String getAttrType() {
		return this.attrType;
	}

	public void setAttrType(String attrType) {
		this.attrType = attrType;
	}

	@Column(name = "attr_value", nullable = false)
	public String getAttrValue() {
		return this.attrValue;
	}

	public void setAttrValue(String attrValue) {
		this.attrValue = attrValue;
	}

	@Column(name = "user_updated")
	public Boolean getUserUpdated() {
		return this.userUpdated;
	}

	public void setUserUpdated(Boolean userUpdated) {
		this.userUpdated = userUpdated;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_modified", length = 35)
	public Date getLastModified() {
		return this.lastModified;
	}

	public void setLastModified(Date lastModified) {
		this.lastModified = lastModified;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "itemAttribute")
	@Cascade(CascadeType.ALL)
	public Set<ItemAttribute> getItemAttributes() {
		return this.itemAttributes;
	}

	public void setItemAttributes(Set<ItemAttribute> itemAttributes) {
		this.itemAttributes = itemAttributes;
	}

}
