package au.edu.anu.metadatastores.datamodel.store;

// Generated 27/02/2013 10:39:19 AM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PotentialRelationId generated by hbm2java
 */
@Embeddable
public class PotentialRelationId implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	private Long iid;
	private String relationValue;
	private Long relatedIid;

	public PotentialRelationId() {
	}

	public PotentialRelationId(Long iid, String relationValue, Long relatedIid) {
		this.iid = iid;
		this.relationValue = relationValue;
		this.relatedIid = relatedIid;
	}

	@Column(name = "iid", nullable = false)
	public Long getIid() {
		return this.iid;
	}

	public void setIid(Long iid) {
		this.iid = iid;
	}

	@Column(name = "relation_value", nullable = false)
	public String getRelationValue() {
		return this.relationValue;
	}

	public void setRelationValue(String relationValue) {
		this.relationValue = relationValue;
	}

	@Column(name = "related_iid", nullable = false)
	public Long getRelatedIid() {
		return this.relatedIid;
	}

	public void setRelatedIid(Long relatedIid) {
		this.relatedIid = relatedIid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PotentialRelationId))
			return false;
		PotentialRelationId castOther = (PotentialRelationId) other;

		return (this.getIid().equals(castOther.getIid()))
				&& ((this.getRelationValue() == castOther.getRelationValue()) || (this
						.getRelationValue() != null
						&& castOther.getRelationValue() != null && this
						.getRelationValue()
						.equals(castOther.getRelationValue())))
				&& (this.getRelatedIid().equals(castOther.getRelatedIid()));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getIid().intValue();
		result = 37
				* result
				+ (getRelationValue() == null ? 0 : this.getRelationValue()
						.hashCode());
		result = 37 * result + (int) this.getRelatedIid().intValue();
		return result;
	}

}
