package au.edu.anu.metadatastores.datamodel.aries.publications;

// Generated 10/01/2013 4:27:05 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ResearchOutputsJournals generated by hbm2java
 */
@Entity
@Table(name = "research_outputs_journals")
public class ResearchOutputsJournals implements java.io.Serializable {

	private Integer intJournalCode;
	private String chrJournalName;
	private String chrYear;
	private String chrISSN;
	private Set<ResearchOutputsData1> researchOutputsData1s = new HashSet(0);

	public ResearchOutputsJournals() {
	}

	public ResearchOutputsJournals(Integer intJournalCode) {
		this.intJournalCode = intJournalCode;
	}

	public ResearchOutputsJournals(Integer intJournalCode,
			String chrJournalName, String chrYear, Set<ResearchOutputsData1> researchOutputsData1s) {
		this.intJournalCode = intJournalCode;
		this.chrJournalName = chrJournalName;
		this.chrYear = chrYear;
		this.researchOutputsData1s = researchOutputsData1s;
	}

	@Id
	@Column(name = "intJournalCode", unique = true, nullable = false, length = 45)
	public Integer getIntJournalCode() {
		return this.intJournalCode;
	}

	public void setIntJournalCode(Integer intJournalCode) {
		this.intJournalCode = intJournalCode;
	}

	@Column(name = "chrJournalName", length = 45)
	public String getChrJournalName() {
		return this.chrJournalName;
	}

	public void setChrJournalName(String chrJournalName) {
		this.chrJournalName = chrJournalName;
	}

	@Column(name = "chrYear", length = 45)
	public String getChrYear() {
		return this.chrYear;
	}

	public void setChrYear(String chrYear) {
		this.chrYear = chrYear;
	}
	
	@Column(name = "chrISSN", length = 45)
	public String getChrISSN() {
		return chrISSN;
	}

	public void setChrISSN(String chrISSN) {
		this.chrISSN = chrISSN;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "researchOutputsJournals")
	public Set<ResearchOutputsData1> getResearchOutputsData1s() {
		return this.researchOutputsData1s;
	}

	public void setResearchOutputsData1s(Set<ResearchOutputsData1> researchOutputsData1s) {
		this.researchOutputsData1s = researchOutputsData1s;
	}

}
