package au.edu.anu.metadatastores.datamodel.aries.publications;

// Generated 10/01/2013 4:27:05 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.NotFound;
import org.hibernate.annotations.NotFoundAction;

import au.edu.anu.metadatastores.datamodel.aries.grants.ForCodes;

/**
 * ResearchOutputsData1 generated by hbm2java
 */
@Entity
@Table(name = "research_outputs_data1")
public class ResearchOutputsData1 implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	
	private String chrOutput6code;
	private ResearchOutputsConferences researchOutputsConferences;
	private ResearchOutputsJournals researchOutputsJournals;
	private ResearchOutputsBooks researchOutputsBooks;
	private ResearchOutputsLevel2 researchOutputsLevel2;
	private String chrPublicationTitle;
	private String chrReportingYear;
	private String chrFirstNamedAuthor;
	private ForCodes forCodes1;
	private String chrForpercentage1;
	private ForCodes forCodes2;
	private String chrForpercentage2;
	private ForCodes forCodes3;
	private String chrForpercentage3;
	private String chrISSN;
	private String chrISBN;
	private Set<ResearchOutputsDataAuthors> researchOutputsDataAuthorses = new HashSet<ResearchOutputsDataAuthors>(0);

	public ResearchOutputsData1() {
	}

	public ResearchOutputsData1(String chrOutput6code) {
		this.chrOutput6code = chrOutput6code;
	}

	public ResearchOutputsData1(String chrOutput6code,
			ResearchOutputsConferences researchOutputsConferences,
			ResearchOutputsJournals researchOutputsJournals,
			String chrPublicationTitle, String chrFirstNamedAuthor,
			Set<ResearchOutputsDataAuthors> researchOutputsDataAuthorses) {
		this.chrOutput6code = chrOutput6code;
		this.researchOutputsConferences = researchOutputsConferences;
		this.researchOutputsJournals = researchOutputsJournals;
		this.chrPublicationTitle = chrPublicationTitle;
		this.chrFirstNamedAuthor = chrFirstNamedAuthor;
		this.researchOutputsDataAuthorses = researchOutputsDataAuthorses;
	}

	@Id
	@Column(name = "chrOutput6Code", unique = true, nullable = false, length = 45)
	public String getChrOutput6code() {
		return this.chrOutput6code;
	}

	public void setChrOutput6code(String chrOutput6code) {
		this.chrOutput6code = chrOutput6code;
	}

	@Column(name="chrReportingYear", length = 45)
	public String getChrReportingYear() {
		return chrReportingYear;
	}

	public void setChrReportingYear(String chrReportingYear) {
		this.chrReportingYear = chrReportingYear;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "intConferenceCode")
	public ResearchOutputsConferences getResearchOutputsConferences() {
		return this.researchOutputsConferences;
	}

	public void setResearchOutputsConferences(
			ResearchOutputsConferences researchOutputsConferences) {
		this.researchOutputsConferences = researchOutputsConferences;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "intJournalCode")
	public ResearchOutputsJournals getResearchOutputsJournals() {
		return this.researchOutputsJournals;
	}

	public void setResearchOutputsJournals(
			ResearchOutputsJournals researchOutputsJournals) {
		this.researchOutputsJournals = researchOutputsJournals;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "intBookCode")
	public ResearchOutputsBooks getResearchOutputsBooks() {
		return this.researchOutputsBooks;
	}

	public void setResearchOutputsBooks(ResearchOutputsBooks researchOutputsBooks) {
		this.researchOutputsBooks = researchOutputsBooks;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "chrOutput3Code")
	public ResearchOutputsLevel2 getResearchOutputsLevel2() {
		return this.researchOutputsLevel2;
	}

	public void setResearchOutputsLevel2(ResearchOutputsLevel2 researchOutputsLevel2) {
		this.researchOutputsLevel2 = researchOutputsLevel2;
	}

	@Column(name = "chrPublicationTitle", length = 45)
	public String getChrPublicationTitle() {
		return this.chrPublicationTitle;
	}

	public void setChrPublicationTitle(String chrPublicationTitle) {
		this.chrPublicationTitle = chrPublicationTitle;
	}

	@Column(name = "chrFirstNamedAuthor", length = 45)
	public String getChrFirstNamedAuthor() {
		return this.chrFirstNamedAuthor;
	}

	public void setChrFirstNamedAuthor(String chrFirstNamedAuthor) {
		this.chrFirstNamedAuthor = chrFirstNamedAuthor;
	}

	@Column(name = "chrFORpercentage1", length = 45)
	public String getChrForpercentage1() {
		return this.chrForpercentage1;
	}

	public void setChrForpercentage1(String chrForpercentage1) {
		this.chrForpercentage1 = chrForpercentage1;
	}

	@Column(name = "chrFORpercentage2", length = 45)
	public String getChrForpercentage2() {
		return this.chrForpercentage2;
	}

	public void setChrForpercentage2(String chrForpercentage2) {
		this.chrForpercentage2 = chrForpercentage2;
	}

	@Column(name = "chrFORpercentage3", length = 45)
	public String getChrForpercentage3() {
		return this.chrForpercentage3;
	}

	public void setChrForpercentage3(String chrForpercentage3) {
		this.chrForpercentage3 = chrForpercentage3;
	}

	@Column(name = "chrISSN", length = 45)
	public String getChrISSN() {
		return chrISSN;
	}

	public void setChrISSN(String chrISSN) {
		this.chrISSN = chrISSN;
	}

	@Column(name = "chrISBN", length = 45)
	public String getChrISBN() {
		return chrISBN;
	}

	public void setChrISBN(String chrISBN) {
		this.chrISBN = chrISBN;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "researchOutputsData1")
	public Set<ResearchOutputsDataAuthors> getResearchOutputsDataAuthorses() {
		return this.researchOutputsDataAuthorses;
	}

	public void setResearchOutputsDataAuthorses(Set<ResearchOutputsDataAuthors> researchOutputsDataAuthorses) {
		this.researchOutputsDataAuthorses = researchOutputsDataAuthorses;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "chrFORcode1")
	@NotFound(action=NotFoundAction.IGNORE)
	public ForCodes getForCodes1() {
		return forCodes1;
	}

	public void setForCodes1(ForCodes forCodes1) {
		this.forCodes1 = forCodes1;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "chrFORcode2")
	@NotFound(action=NotFoundAction.IGNORE)
	public ForCodes getForCodes2() {
		return forCodes2;
	}

	public void setForCodes2(ForCodes forCodes2) {
		this.forCodes2 = forCodes2;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "chrFORcode3")
	@NotFound(action=NotFoundAction.IGNORE)
	public ForCodes getForCodes3() {
		return forCodes3;
	}

	public void setForCodes3(ForCodes forCodes3) {
		this.forCodes3 = forCodes3;
	}

}
