package au.edu.anu.metadatastores.datamodel.aries.publications;

// Generated 10/01/2013 4:27:05 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ResearchOutputsDataAuthors generated by hbm2java
 */
@Entity
@Table(name = "research_outputs_data_authors")
public class ResearchOutputsDataAuthors implements java.io.Serializable {

	private String chrOutputInvestigatorCode;
	private ResearchOutputsData1 researchOutputsData1;
	private String chrStatus;
	private String chrRoleCode;
	//GT Added
	private String chrStaffNumber;
	private String chrOrder;

	public ResearchOutputsDataAuthors() {
	}

	public ResearchOutputsDataAuthors(String chrOutputInvestigatorCode) {
		this.chrOutputInvestigatorCode = chrOutputInvestigatorCode;
	}

	public ResearchOutputsDataAuthors(String chrOutputInvestigatorCode,
			ResearchOutputsData1 researchOutputsData1, String chrStatus,
			String chrRoleCode) {
		this.chrOutputInvestigatorCode = chrOutputInvestigatorCode;
		this.researchOutputsData1 = researchOutputsData1;
		this.chrStatus = chrStatus;
		this.chrRoleCode = chrRoleCode;
	}

	@Id
	@Column(name = "chrOutputInvestigatorCode", unique = true, nullable = false, length = 45)
	public String getChrOutputInvestigatorCode() {
		return this.chrOutputInvestigatorCode;
	}

	public void setChrOutputInvestigatorCode(String chrOutputInvestigatorCode) {
		this.chrOutputInvestigatorCode = chrOutputInvestigatorCode;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "chrOutput6Code")
	public ResearchOutputsData1 getResearchOutputsData1() {
		return this.researchOutputsData1;
	}

	public void setResearchOutputsData1(
			ResearchOutputsData1 researchOutputsData1) {
		this.researchOutputsData1 = researchOutputsData1;
	}

	@Column(name = "chrStatus", length = 45)
	public String getChrStatus() {
		return this.chrStatus;
	}

	public void setChrStatus(String chrStatus) {
		this.chrStatus = chrStatus;
	}

	@Column(name = "chrRoleCode", length = 45)
	public String getChrRoleCode() {
		return this.chrRoleCode;
	}

	public void setChrRoleCode(String chrRoleCode) {
		this.chrRoleCode = chrRoleCode;
	}

	//GT added
	@Column(name = "chrStaffNumber", length = 45)
	public String getChrStaffNumber() {
		return this.chrStaffNumber;
	}
	
	public void setchrStaffNumber(String chrStaffNumber) {
		this.chrStaffNumber = chrStaffNumber;
	}
	
	@Column(name = "chrOrder", length = 45)
	public String getChrOrder() {
		return this.chrOrder;
	}
	
	public void setChrOrder(String chrOrder) {
		this.chrOrder = chrOrder;
	}
}
