package au.edu.anu.metadatastores.datamodel.aries.publications;

// Generated 10/01/2013 4:27:05 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ResearchOutputsConferences generated by hbm2java
 */
@Entity
@Table(name = "research_outputs_conferences")
public class ResearchOutputsConferences implements java.io.Serializable {

	private Integer intConferenceCode;
	private String chrConferenceName;
	private String chrYear;
	private String chrISBN;
	private Set<ResearchOutputsData1> researchOutputsData1s = new HashSet<ResearchOutputsData1>(0);

	public ResearchOutputsConferences() {
	}

	public ResearchOutputsConferences(Integer intConferenceCode) {
		this.intConferenceCode = intConferenceCode;
	}

	public ResearchOutputsConferences(Integer intConferenceCode,
			String chrConferenceName, String chrYear, Set<ResearchOutputsData1> researchOutputsData1s) {
		this.intConferenceCode = intConferenceCode;
		this.chrConferenceName = chrConferenceName;
		this.chrYear = chrYear;
		this.researchOutputsData1s = researchOutputsData1s;
	}

	@Id
	@Column(name = "intConferenceCode", unique = true, nullable = false, length = 45)
	public Integer getIntConferenceCode() {
		return this.intConferenceCode;
	}

	public void setIntConferenceCode(Integer intConferenceCode) {
		this.intConferenceCode = intConferenceCode;
	}

	@Column(name = "chrConferenceName", length = 45)
	public String getChrConferenceName() {
		return this.chrConferenceName;
	}

	public void setChrConferenceName(String chrConferenceName) {
		this.chrConferenceName = chrConferenceName;
	}

	@Column(name = "chrYear", length = 45)
	public String getChrYear() {
		return this.chrYear;
	}

	public void setChrYear(String chrYear) {
		this.chrYear = chrYear;
	}
	
	@Column(name = "chrISBN", length = 45)
	public String getChrISBN() {
		return chrISBN;
	}

	public void setChrISBN(String chrISBN) {
		this.chrISBN = chrISBN;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "researchOutputsConferences")
	public Set<ResearchOutputsData1> getResearchOutputsData1s() {
		return this.researchOutputsData1s;
	}

	public void setResearchOutputsData1s(Set<ResearchOutputsData1> researchOutputsData1s) {
		this.researchOutputsData1s = researchOutputsData1s;
	}

}
